### ISSUE TITLE
GCS Storage is very slow to split files in the context of a ForEachItem

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/storage-gcs#112]
### Expected Behavior

Splitting files should be quick

### Actual Behaviour

For example with this flow:

```yaml
id: orders_parallel
namespace: prod

tasks:
  - id: extract
    type: io.kestra.plugin.jdbc.duckdb.Query
    sql: |
      INSTALL httpfs;
      LOAD httpfs;
      SELECT *
      FROM read_csv_auto('https://raw.githubusercontent.com/kestra-io/datasets/main/csv/orders.csv', header=True);
    store: true

  - id: each
    type: io.kestra.core.tasks.flows.ForEachItem
    items: "{{ outputs.extract.uri }}"
    batch:
      rows: 1
    namespace: prod
    flowId: orders
    wait: true # wait for the subflow execution
    transmitFailed: true # fail the task run if the subflow execution fails
    inputs:
      order: "{{ taskrun.items }}" # special variable that contains the items of the batch
```

The ForEachItem split step took less than 100ms with the Local storage but more than 2mn30s with he Google Cloud Storage!

### Environment Information

- Kestra Version: 0.15
- Plugin version: 
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):
